name: Build README and deploy Datasette

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      # We need full history to introspect created/updated:
      with:
        fetch-depth: 0
        path: main
    - name: Checkout til-db
      uses: actions/checkout@v2
      with:
        repository: wildandhya/til-db
        path: til-db
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN_FOR_PUSH }}
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r main/requirements.txt
    - name: Install npm dependencies
      run: sudo npm install -g puppeteer-cli --unsafe-perm=true
    - name: Download previous database unless REBUILD in commit message
      if: |-
        !contains(github.event.head_commit.message, 'REBUILD')
      run: |
        curl -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN_FOR_PUSH }}" \
         --fail -o main/tils.db \
         https://raw.githubusercontent.com/wildandhya/til-db/main/tils.db
      continue-on-error: true
    - name: Build database
      run: |-
        mkdir -p main
        cd main
        python build_database.py
    # - name: Soundness check
    #   run: |-
    #     cd main
    #     datasette . --get / | grep "Wildan: TIL"
    # - name: Generate missing screenshots
    #   run: |-
    #     cd main
    #     python generate_screenshots.py
    # - name: Debug Git
    #   run: |-
    #     echo "Current user:"
    #     git config --get user.name
    #     git config --get user.email
    #     echo "Repository Status:"
    #     git status
    - name: Update README
      run: |-
        cd main
        python update_readme.py --rewrite
        cat README.md
    - name: Commit and push if README changed
      run: |-
        cd main
        git diff
        git config --global user.email "wildandhya15@gmail.com"
        git config --global user.name "wildandhya"
        git diff --quiet || (git add README.md && git commit -m "Updated README")
        git push
    - name: Save tils.db to wildandhya/til-db
      run: |-
        cd til-db
        cp ../main/tils.db .
        git add tils.db
        git commit --amend --no-edit
        git push --force
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'
    - name: Deploy Datasette using Vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: |-
        cd main
        datasette publish vercel tils.db \
          --token $VERCEL_TOKEN \
          --project wildandhyas-projects \
          --metadata metadata.yaml \
          --static static:static \
          --install datasette-template-sql \
          --install "datasette-atom>=0.7" \
          --install datasette-json-html \
          --install beautifulsoup4 \
          --install datasette-debug-asgi \
          --install "datasette-graphql>=0.12" \
          --install datasette-media \
          --plugins-dir plugins \
          --template-dir templates \
          --public

          